/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
    "./src/ui/**/*.html",
    "./src/pages/**/*.html",
    "./src/layouts/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        st: {
          /* bg colors migrated to global.css @theme for v4 compatibility */
          node: {
            outer: 'var(--st-node-outer)',
            inner: 'var(--st-node-inner)',
            stroke: 'var(--st-node-stroke)',
          },
          comprendre: 'var(--st-comprendre)',
          concevoir: 'var(--st-concevoir)',
          exprimer: 'var(--st-exprimer)',
          developper: 'var(--st-developper)',
          entreprendre: 'var(--st-entreprendre)',
          accent: {
            orange: 'var(--st-accent-orange)',
          },
          star: {
            fill: 'var(--st-star-fill)',
            stroke: 'var(--st-star-stroke)',
          },
          chart: {
            purple: 'var(--st-chart-purple)',
            pink: 'var(--st-chart-pink)',
            green: 'var(--st-chart-green)',
          },
          line: {
            concevoir: 'var(--st-line-concevoir)',
          },
        },
      },
    },
  },
  safelist: [
    // Dynamic class patterns that need to be preserved
    {
      pattern: /^(bg|text|border|ring|shadow|divide|fill|stroke)-(slate|blue|red|green|yellow|purple|orange)-(50|100|200|300|400|500|600|700|800|900)/,
      variants: ['hover', 'focus', 'group-hover'],
    },
    {
      pattern: /^(w|h|p|m|gap|rounded)-(0|1|2|3|4|6|8|10|12|16|20|24|32|40|48|56|64)/,
    },
    {
      pattern: /^text-\[0\.\d+rem\]/,
    },
    {
      pattern: /^(px|py)-(0\.25|0\.5|1|2|3|4)/,
    },
    // Specific classes
    'level-btn',
    'level-btn-active',
    'indicator-box',
    'indicator-active',
    'progress-bar',
    'ac-item',
    'ac-header',
    'ac-body',
    'block',
    'flex',
    'grid',
    'grid-cols-6',
    'grid-cols-3',
    'gap-2',
    'gap-3',
    'gap-4',
    'space-y-2',
    'space-y-3',
    'space-y-4',
    'overflow-hidden',
    'rounded-lg',
    'rounded-xl',
    'border',
    'transition-all',
    'duration-300',
    'duration-500',
    'ease-out',
    'ease-in',
    'hover:cursor-pointer',
    'hover:border-slate-600',
    'hover:bg-slate-700/50',
    'hover:text-white',
    'list-none',
    'select-none',
    'items-center',
    'items-start',
    'justify-between',
    'justify-center',
    'flex-shrink-0',
    'flex-grow',
    'p-3',
    'p-4',
    'p-6',
    'mt-1',
    'mb-1',
    'mb-2',
    'mb-3',
    'pt-4',
    'h-1',
    'h-1.5',
    'h-6',
    'h-16',
    'w-5',
    'w-6',
    'w-full',
    'w-48',
    'font-bold',
    'font-semibold',
    'font-medium',
    'text-xs',
    'text-sm',
    'text-lg',
    'text-xl',
    'uppercase',
    'tracking-wider',
    'tracking-widest',
    'bg-slate-800',
    'bg-slate-800/30',
    'bg-slate-800/50',
    'bg-slate-800/80',
    'bg-slate-900',
    'bg-slate-900/95',
    'bg-gradient-to-r',
    'from-slate-800',
    'to-slate-700',
    'hover:from-slate-700',
    'hover:to-slate-600',
    'border-slate-600',
    'border-slate-700',
    'border-slate-700/30',
    'border-slate-700/50',
    'border-slate-800',
    'text-slate-300',
    'text-slate-400',
    'text-slate-500',
    'text-white',
  ],
  plugins: [],
}

